/**
 * @file flutter formatter
 * @description Generated/formatting utilities used by FlyRank Visual DNA.
 */

import { createReferenceResolver, ReferenceResolver } from "@/helpers/design-token.helpers";
import {
  FLUTTER_CLASS_NAME,
  FLUTTER_DART_FILE_TEMPLATE,
  FLUTTER_IMPORT_SNIPPET,
  FLUTTER_THEME_FN_NAME,
} from "@/constants/flutter/flutter.constants";
import {
  type DesignTokensBase,
  type TokenNode,
  type TokenRef,
  walkTokenLeaves,
} from "@/helpers/formatter-token.helpers";

type DesignTokens = DesignTokensBase;

interface SemanticColorEntry {
  name: string;
  path: string;
}

class FlutterDartGenerator {
  private tokens: DesignTokens;
  private headerVersion: string = "7.0.0";
  private tokenResolver: ReferenceResolver;

  constructor(tokens: DesignTokens) {
    this.tokens = tokens;
    this.tokenResolver = createReferenceResolver(this.tokens as Record<string, TokenNode>);
  }

  private camelFromPath(path: string): string {
    const parts = path.split(".");
    const trimmed = parts.slice(1);
    let segs: string[];

    if (trimmed[0] === "color" && trimmed.length >= 3) {
      segs = trimmed.slice(1);
    } else {
      segs = trimmed;
    }

    return segs
      .map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)))
      .join("")
      .replace(/[^a-zA-Z0-9]/g, "");
  }

  private hexToDartArgb(hex: unknown): string | null {
    if (typeof hex !== "string") return null;
    let h = hex.trim().replace(/^#/, "");
    if (h.length === 3)
      h = h
        .split("")
        .map((c) => c + c)
        .join("");
    if (h.length === 6 && /^[0-9a-fA-F]{6}$/.test(h))
      return `0xFF${h.toUpperCase()}`;
    if (h.length === 8 && /^[0-9a-fA-F]{8}$/.test(h))
      return `0x${h.toUpperCase()}`;
    return null;
  }

  private dimensionToNumber(value: unknown): number | null {
    if (typeof value === "number") return value;
    if (typeof value !== "string") return null;
    const m = value.match(/^(-?\d+(?:\.\d+)?)(px|pt|dp|rem|em)?$/);
    if (!m) return null;
    const n = parseFloat(m[1]);
    if (m[2] === "rem" || m[2] === "em") return n * 16;
    return n;
  }

  private generateHeader(): string[] {
    const lines: string[] = [];
    const source = this.tokens?.$metadata?.source || "";
    lines.push(`// Generated by FlyRank Visual DNA v${this.headerVersion}`);
    if (source) lines.push(`// Source: ${source}`);
    lines.push(FLUTTER_IMPORT_SNIPPET);
    lines.push("");
    return lines;
  }

  private generateDesignTokensClass(): string[] {
    const lines: string[] = [];
    const semEntries: SemanticColorEntry[] = [];

    lines.push(`class ${FLUTTER_CLASS_NAME} {`);
    lines.push(`  ${FLUTTER_CLASS_NAME}._();`);
    lines.push("");

    // Semantic colors
    const semColor = this.tokens?.semantic?.color;
    if (semColor) {
      lines.push("  // Semantic");
      for (const leaf of walkTokenLeaves(semColor, "semantic.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const argb = this.hexToDartArgb(resolved);
        if (!argb) continue;
        const name = this.camelFromPath(leaf.path);
        lines.push(`  static const Color ${name} = Color(${argb});`);
        semEntries.push({ name, path: leaf.path });
      }
    }

    // Primitive spacing
    const spacing = this.tokens?.primitive?.spacing || {};
    for (const key of Object.keys(spacing)) {
      const tok = spacing[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.spacing.${key}`),
      );
      if (n == null) continue;
      lines.push(
        `  static const double ${this.camelFromPath(`primitive.spacing.${key}`)} = ${n};`,
      );
    }

    // Primitive radius
    const radius = this.tokens?.primitive?.radius || {};
    for (const key of Object.keys(radius)) {
      const tok = radius[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.radius.${key}`),
      );
      if (n == null) continue;
      lines.push(
        `  static const double ${this.camelFromPath(`primitive.radius.${key}`)} = ${n};`,
      );
    }

    // Primitive colors
    const primColor = this.tokens?.primitive?.color;
    if (primColor) {
      lines.push("");
      lines.push("  // Primitive palette");
      for (const leaf of walkTokenLeaves(primColor, "primitive.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const argb = this.hexToDartArgb(resolved);
        if (!argb) continue;
        lines.push(
          `  static const Color ${this.camelFromPath(leaf.path)} = Color(${argb});`,
        );
      }
    }

    lines.push("}");
    return lines;
  }

  private generateThemeHelper(semEntries: SemanticColorEntry[]): string[] {
    const lines: string[] = [];
    const hasActionPrimary = semEntries.some((e) => e.name === "actionPrimary");
    const hasSurfaceDefault = semEntries.some(
      (e) => e.name === "surfaceDefault",
    );

    lines.push(`ThemeData ${FLUTTER_THEME_FN_NAME}() {`);
    lines.push("  return ThemeData(");
    lines.push("    colorScheme: const ColorScheme.light(");
    if (hasActionPrimary)
      lines.push(`      primary: ${FLUTTER_CLASS_NAME}.actionPrimary,`);
    if (hasSurfaceDefault)
      lines.push(`      surface: ${FLUTTER_CLASS_NAME}.surfaceDefault,`);
    lines.push("    ),");
    lines.push("  );");
    lines.push("}");

    return lines;
  }

  public format(): string {
    const header = this.generateHeader().join("\n");
    const tokensClass = this.generateDesignTokensClass().join("\n");
    const themeHelper = this.generateThemeHelper(this.collectSemanticColors()).join("\n");

    return FLUTTER_DART_FILE_TEMPLATE
      .replace("{{header}}", header)
      .replace("{{tokensClass}}", tokensClass)
      .replace("{{themeHelper}}", themeHelper)
      .trimEnd() + "\n";
  }

  private collectSemanticColors(): SemanticColorEntry[] {
    const entries: SemanticColorEntry[] = [];
    const semColor = this.tokens?.semantic?.color;

    if (semColor) {
      for (const leaf of walkTokenLeaves(semColor, "semantic.color")) {
        if (leaf.token.$type !== "color") continue;
        const name = this.camelFromPath(leaf.path);
        entries.push({ name, path: leaf.path });
      }
    }

    return entries;
  }
}

export function formatFlutterDart(tokens: DesignTokens): string {
  const generator = new FlutterDartGenerator(tokens);
  return generator.format();
}
