/**
 * @file jetpack compose formatter
 * @description Generated/formatting utilities used by FlyRank Visual DNA.
 */

import { createReferenceResolver, ReferenceResolver } from "@/helpers/design-token.helpers";
import {
  JETPACK_OBJECT_NAME,
  JETPACK_PACKAGE_NAME,
  JETPACK_THEME_KT_TEMPLATE,
  JETPACK_XML_TEMPLATE,
} from "@/constants/android/jetpack.constants";
import {
  type DesignTokensBase,
  type TokenNode,
  type TokenRef,
  walkTokenLeaves,
} from "@/helpers/formatter-token.helpers";

type DesignTokens = DesignTokensBase;

interface ColorEntry {
  path: string;
  argb: string;
}

interface DimensionEntry {
  path: string;
  value: number;
}

class AndroidComposeGenerator {
  private tokens: DesignTokens;
  private tokenResolver: ReferenceResolver;
  private headerVersion: string = "7.0.0";

  constructor(tokens: DesignTokens) {
    this.tokens = tokens;
    this.tokenResolver = createReferenceResolver(this.tokens as Record<string, TokenNode>);
  }

  private pascalFromPath(path: string): string {
    const parts = path.split(".");
    const trimmed = parts.slice(1);
    let segs: string[];

    if (trimmed[0] === "color" && trimmed.length >= 3) {
      segs = trimmed.slice(1);
    } else {
      segs = trimmed;
    }

    return segs
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join("")
      .replace(/[^a-zA-Z0-9]/g, "");
  }

  private snakeFromPath(path: string): string {
    const parts = path.split(".");
    const trimmed = parts.slice(1);
    let segs: string[];

    if (trimmed[0] === "color" && trimmed.length >= 3) {
      segs = trimmed.slice(1);
    } else {
      segs = trimmed;
    }

    return segs
      .map((s) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase())
      .join("_")
      .replace(/[^a-z0-9_]/g, "");
  }

  private hexToArgb(hex: unknown): string | null {
    if (typeof hex !== "string") return null;
    let h = hex.trim().replace(/^#/, "");
    if (h.length === 3)
      h = h
        .split("")
        .map((c) => c + c)
        .join("");
    if (h.length === 6 && /^[0-9a-fA-F]{6}$/.test(h))
      return `FF${h.toUpperCase()}`;
    if (h.length === 8 && /^[0-9a-fA-F]{8}$/.test(h)) return h.toUpperCase();
    return null;
  }

  private dimensionToNumber(value: unknown): number | null {
    if (typeof value === "number") return value;
    if (typeof value !== "string") return null;
    const m = value.match(/^(-?\d+(?:\.\d+)?)(px|pt|dp|rem|em)?$/);
    if (!m) return null;
    const n = parseFloat(m[1]);
    if (m[2] === "rem" || m[2] === "em") return n * 16;
    return n;
  }

  private collectColors(): ColorEntry[] {
    const entries: ColorEntry[] = [];

    const sem = this.tokens?.semantic?.color;
    if (sem) {
      for (const leaf of walkTokenLeaves(sem, "semantic.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const argb = this.hexToArgb(resolved);
        if (!argb) continue;
        entries.push({ path: leaf.path, argb });
      }
    }

    const prim = this.tokens?.primitive?.color;
    if (prim) {
      for (const leaf of walkTokenLeaves(prim, "primitive.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const argb = this.hexToArgb(resolved);
        if (!argb) continue;
        entries.push({ path: leaf.path, argb });
      }
    }

    return entries;
  }

  private collectDimensions(): DimensionEntry[] {
    const entries: DimensionEntry[] = [];

    const spacing = this.tokens?.primitive?.spacing || {};
    for (const key of Object.keys(spacing)) {
      const tok = spacing[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.spacing.${key}`),
      );
      if (n == null) continue;
      entries.push({ path: `primitive.spacing.${key}`, value: n });
    }

    const radius = this.tokens?.primitive?.radius || {};
    for (const key of Object.keys(radius)) {
      const tok = radius[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.radius.${key}`),
      );
      if (n == null) continue;
      entries.push({ path: `primitive.radius.${key}`, value: n });
    }

    return entries;
  }

  private buildThemeKt(colors: ColorEntry[], dims: DimensionEntry[]): string {
    const source = this.tokens?.$metadata?.source || "";
    const headerLines = [`// Generated by FlyRank Visual DNA v${this.headerVersion}`];
    if (source) headerLines.push(`// Source: ${source}`);
    const bodyLines: string[] = [];

    for (const { path, argb } of colors) {
      bodyLines.push(`    val ${this.pascalFromPath(path)} = Color(0x${argb})`);
    }
    for (const { path, value } of dims) {
      bodyLines.push(`    val ${this.pascalFromPath(path)} = ${value}.dp`);
    }

    return JETPACK_THEME_KT_TEMPLATE
      .replace("{{header}}", headerLines.join("\n"))
      .replace("{{packageName}}", JETPACK_PACKAGE_NAME)
      .replace("{{objectName}}", JETPACK_OBJECT_NAME)
      .replace("{{body}}", bodyLines.join("\n"))
      .trimEnd() + "\n";
  }

  private buildColorsXml(colors: ColorEntry[]): string {
    const bodyLines: string[] = [];
    for (const { path, argb } of colors) {
      bodyLines.push(`    <color name="${this.snakeFromPath(path)}">#${argb}</color>`);
    }
    return JETPACK_XML_TEMPLATE.replace("{{body}}", bodyLines.join("\n")).trimEnd() + "\n";
  }

  private buildDimensXml(dims: DimensionEntry[]): string {
    const bodyLines: string[] = [];
    for (const { path, value } of dims) {
      bodyLines.push(`    <dimen name="${this.snakeFromPath(path)}">${value}dp</dimen>`);
    }
    return JETPACK_XML_TEMPLATE.replace("{{body}}", bodyLines.join("\n")).trimEnd() + "\n";
  }

  public generate(): Record<string, string> {
    const colors = this.collectColors();
    const dims = this.collectDimensions();

    return {
      "Theme.kt": this.buildThemeKt(colors, dims),
      "colors.xml": this.buildColorsXml(colors),
      "dimens.xml": this.buildDimensXml(dims),
    };
  }
}

export function formatAndroidCompose(
  tokens: DesignTokens,
): Record<string, string> {
  const generator = new AndroidComposeGenerator(tokens);
  return generator.generate();
}
