/**
 * @file swiftui formatter
 * @description Generated/formatting utilities used by FlyRank Visual DNA.
 */

import { createReferenceResolver, ReferenceResolver } from "@/helpers/design-token.helpers";
import {
  SWIFTUI_CG_EXTENSION_HEADER,
  SWIFTUI_COLOR_EXTENSION_HEADER,
  SWIFTUI_IMPORT_SNIPPET,
} from "@/constants/ios/swiftui.constants";
import {
  type DesignTokensBase,
  type TokenNode,
  type TokenRef,
  tokenPathToCamel,
  walkTokenLeaves,
} from "@/helpers/formatter-token.helpers";

type DesignTokens = DesignTokensBase;

class SwiftUIFormatter {
  private tokenResolver: ReferenceResolver;
  private tokens: DesignTokens;
  private headerVersion: string = "7.0.0";


  constructor(tokens: DesignTokens) {
    this.tokens = tokens;
    this.tokenResolver = createReferenceResolver(this.tokens as Record<string, TokenNode>);
  }
  

  private camelFromPath(path: string): string {
    return tokenPathToCamel(path);
  }

  private hexToSwiftHex(hex: unknown): string | null {
    if (typeof hex !== "string") return null;
    let h = hex.trim().replace(/^#/, "");
    if (h.length === 3) {
      h = h
        .split("")
        .map((c) => c + c)
        .join("");
    }
    if (h.length === 6 && /^[0-9a-fA-F]{6}$/.test(h)) {
      return `0x${h.toUpperCase()}`;
    }
    if (h.length === 8 && /^[0-9a-fA-F]{8}$/.test(h)) {
      return `0x${h.slice(2).toUpperCase()}`;
    }
    return null;
  }

  private dimensionToNumber(value: unknown): number | null {
    if (typeof value === "number") return value;
    if (typeof value !== "string") return null;
    const m = value.match(/^(-?\d+(?:\.\d+)?)(px|pt|rem|em)?$/);
    if (!m) return null;
    const n = parseFloat(m[1]);
    const unit = m[2];
    if (unit === "rem" || unit === "em") return n * 16;
    return n;
  }

  private generateHeader(): string[] {
    const lines: string[] = [];
    const source = this.tokens?.$metadata?.source || "";
    lines.push(
      `// Generated by FlyRank Visual DNA v${this.headerVersion}`,
    );
    if (source) lines.push(`// Source: ${source}`);
    lines.push(SWIFTUI_IMPORT_SNIPPET);
    lines.push("");
    return lines;
  }

  private generateColorExtension(): string[] {
    const lines: string[] = [];
    lines.push(SWIFTUI_COLOR_EXTENSION_HEADER);
    lines.push("  init(hex: UInt32) {");
    lines.push("    let r = Double((hex >> 16) & 0xFF) / 255");
    lines.push("    let g = Double((hex >> 8) & 0xFF) / 255");
    lines.push("    let b = Double(hex & 0xFF) / 255");
    lines.push("    self.init(red: r, green: g, blue: b)");
    lines.push("  }");
    lines.push("");
    lines.push("  // MARK: Semantic");

    const semanticColor = this.tokens?.semantic?.color;
    if (semanticColor) {
      for (const leaf of walkTokenLeaves(semanticColor, "semantic.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const swiftHex = this.hexToSwiftHex(resolved);
        if (!swiftHex) continue;
        lines.push(
          `  static let ${this.camelFromPath(leaf.path)} = Color(hex: ${swiftHex})`,
        );
      }
    }

    lines.push("}");
    return lines;
  }

  private generateCGFloatExtension(): string[] {
    const lines: string[] = [];
    lines.push(SWIFTUI_CG_EXTENSION_HEADER);
    lines.push("  // MARK: Primitive spacing");

    const spacing = this.tokens?.primitive?.spacing || {};
    for (const key of Object.keys(spacing)) {
      const tok = spacing[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.spacing.${key}`),
      );
      if (n == null) continue;
      const name = this.camelFromPath(`primitive.spacing.${key}`);
      lines.push(`  static let ${name}: CGFloat = ${n}`);
    }

    lines.push("");
    lines.push("  // MARK: Primitive radius");

    const radius = this.tokens?.primitive?.radius || {};
    for (const key of Object.keys(radius)) {
      const tok = radius[key];
      if (!tok || (tok as TokenRef).$type !== "dimension") continue;
      const n = this.dimensionToNumber(
        this.tokenResolver.resolve(`primitive.radius.${key}`),
      );
      if (n == null) continue;
      const name = this.camelFromPath(`primitive.radius.${key}`);
      lines.push(`  static let ${name}: CGFloat = ${n}`);
    }

    lines.push("}");
    return lines;
  }

  private generatePrimitivePalette(): string[] {
    const lines: string[] = [];
    lines.push("// MARK: Primitive palette (for direct use)");
    lines.push("extension Color {");

    const primColor = this.tokens?.primitive?.color;
    if (primColor) {
      for (const leaf of walkTokenLeaves(primColor, "primitive.color")) {
        if (leaf.token.$type !== "color") continue;
        const resolved = this.tokenResolver.resolve(leaf.path);
        const swiftHex = this.hexToSwiftHex(resolved);
        if (!swiftHex) continue;
        lines.push(
          `  static let ${this.camelFromPath(leaf.path)} = Color(hex: ${swiftHex})`,
        );
      }
    }

    lines.push("}");
    return lines;
  }

  private generateTypographyComments(): string[] {
    const lines: string[] = [];
    const typography = this.tokens?.semantic?.typography;

    if (typography) {
      for (const key of Object.keys(typography)) {
        const tok = typography[key];
        if (!tok || (tok as TokenRef).$type !== "typography") continue;
        const v = (tok as TokenRef).$value || {};
        lines.push(
          `// typography.${key}: family=${(v as Record<string, unknown>).fontFamily ?? ""} size=${(v as Record<string, unknown>).fontSize ?? ""} weight=${(v as Record<string, unknown>).fontWeight ?? ""} lineHeight=${(v as Record<string, unknown>).lineHeight ?? ""}`,
        );
      }
    }

    return lines;
  }

  public format(): string {
    const parts: string[][] = [
      this.generateHeader(),
      this.generateColorExtension(),
      [""],
      this.generateCGFloatExtension(),
      [""],
      this.generatePrimitivePalette(),
      [""],
      this.generateTypographyComments(),
    ];

    return parts.flat().join("\n") + "\n";
  }
}

export function formatIosSwiftUI(tokens: DesignTokens): string {
  const formatter = new SwiftUIFormatter(tokens);
  return formatter.format();
}
