/**
 * @file vue formatter
 * @description Generated/formatting utilities used by FlyRank Visual DNA.
 */

import {
  VUE_CSS_EXPORT_NAME,
  VUE_THEME_EXPORT_NAME,
} from "@/constants/vue/vue.constants";

interface Color {
  hex: string;
}

interface FontFamily {
  name: string;
}

interface DesignSystem {
  colors: {
    primary?: Color;
    secondary?: Color;
    accent?: Color;
    neutrals: Color[];
    backgrounds: string[];
    text: string[];
  };
  typography: {
    families: FontFamily[];
  };
  spacing: {
    scale: number[];
  };
  borders: {
    radii: Array<{ label: string; value: number }>;
  };
  shadows: {
    values: Array<{ label: string; raw: string }>;
  };
}

interface VueTheme {
  dark: boolean;
  colors: Record<string, string>;
}

interface CSSVariables {
  [key: string]: string;
}

class VueThemeGenerator {
  private design: DesignSystem;
  private theme: VueTheme;
  private cssVariables: CSSVariables;

  constructor(design: DesignSystem) {
    this.design = design;
    this.theme = { dark: false, colors: {} };
    this.cssVariables = {};
    this.generate();
  }

  private generate(): void {
    this.generateThemeColors();
    this.generateCSSVariables();
  }

  private generateThemeColors(): void {
    if (this.design.colors.primary) {
      this.theme.colors.primary = this.design.colors.primary.hex;
    }
    if (this.design.colors.secondary) {
      this.theme.colors.secondary = this.design.colors.secondary.hex;
    }
    if (this.design.colors.accent) {
      this.theme.colors.accent = this.design.colors.accent.hex;
    }
    if (this.design.colors.backgrounds.length > 0) {
      this.theme.colors.background = this.design.colors.backgrounds[0];
    }
    if (this.design.colors.text.length > 0) {
      this.theme.colors["on-background"] = this.design.colors.text[0];
    }
  }

  private generateCSSVariables(): void {
    if (this.design.colors.primary) {
      this.cssVariables["--dl-color-primary"] = this.design.colors.primary.hex;
    }
    if (this.design.colors.secondary) {
      this.cssVariables["--dl-color-secondary"] =
        this.design.colors.secondary.hex;
    }

    this.design.colors.neutrals.slice(0, 8).forEach((n, i) => {
      this.cssVariables[`--dl-color-neutral-${i + 1}`] = n.hex;
    });

    this.design.spacing.scale.slice(0, 12).forEach((val, i) => {
      this.cssVariables[`--dl-spacing-${i + 1}`] = `${val}px`;
    });

    this.design.borders.radii.forEach((r) => {
      this.cssVariables[`--dl-radius-${r.label}`] = `${r.value}px`;
    });

    if (this.design.typography.families.length > 0) {
      this.cssVariables["--dl-font-primary"] =
        `'${this.design.typography.families[0].name}', sans-serif`;
    }
  }

  private formatTheme(): string {
    const themeLines = [
      "// Vuetify 3 theme configuration",
      "// Generated by FlyRank's Visual Design System",
      "",
      `export const ${VUE_THEME_EXPORT_NAME} = {`,
      "  dark: false,",
      "  colors: {",
    ];

    for (const [key, value] of Object.entries(this.theme.colors)) {
      themeLines.push(`    ${key}: '${value}',`);
    }

    themeLines.push("  },");
    themeLines.push("};");
    return themeLines.join("\n");
  }

  private formatCSSVariables(): string {
    const cssLines = [
      "",
      "// CSS custom properties",
      `export const ${VUE_CSS_EXPORT_NAME} = \``,
      ":root {",
    ];

    for (const [key, value] of Object.entries(this.cssVariables)) {
      cssLines.push(`  ${key}: ${value};`);
    }

    cssLines.push("}");
    cssLines.push("`;");
    return cssLines.join("\n");
  }

  public format(): string {
    return this.formatTheme() + this.formatCSSVariables();
  }
}

export function formatVueTheme(design: DesignSystem): string {
  const generator = new VueThemeGenerator(design);
  return generator.format();
}
