/**
 * @file svelte constants
 * @description Shared generated-code snippets for Svelte formatter output.
 */

export const SVELTE_ROOT_SELECTOR = ":root {";
export const SVELTE_HEADER_COMMENT = "/* Svelte theme - generated by FlyRank Visual DNA */";
